### ISSUE TITLE
ApolloProvider should be placed on App.tsx

### ISSUE THREAD

**Issue by savioserra** [gabrielreisn/pokedex#8]
If you need to create more routes, then you won't need to recreate the ApolloProvider.

https://github.com/gabrielreisn/pokedex/blob/9a8ce4b7a7c7146ffa98de90adedc9b7935b33f5/src/containers/PokemonContainer.tsx#L17

**Comment by gabrielreisn** [comment]
Sure, you're totally right on that. Can you review it, please?
#9

**Comment by savioserra** [comment]
Good job 👌
